
services:
  postgres:
    image: postgres:latest
    container_name: 'PostgresUF'
    environment:
      POSTGRES_DB: my_api_rest
      POSTGRES_USER: me
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  redis:
    image: redis:latest
    container_name: 'RedisUF'
    volumes:
      - redis_data:/data
    networks:
      - redis_network

  api:
    build: ./WebApplication1/
    container_name: 'APIUF'
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: my_api_rest
      POSTGRES_USER: me
      POSTGRES_PASSWORD: password
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis
    networks:
      - redis_network
      - postgres_network

networks:
  redis_network:
  postgres_network:

volumes:
  postgres_data:
  redis_data:
